apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  replicas: 2
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
        - name: workflow-controller
          image: argoproj/workflow-controller:test
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
          command:
            - workflow-controller
          args:
            - --loglevel=warn
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - argoproj/argoexec:test
            - --burst=2048
            - --qps=2048
            - --pod-cleanup-workers=32
            - --workflow-workers=256
            - --workflow-ttl-workers=64
          env:
            - name: RECENTLY_STARTED_POD_DURATION
              value: 20s
            - name: DEFAULT_REQUEUE_TIME
              value: 1m
            - name: MAX_OPERATION_TIME
              value: 10s
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
