apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent
      containers:
        - name: main
          image: argoproj/agent:latest
          securityContext:
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
