apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent
      containers:
        - name: main
          image: argoproj/agent:latest
          ports:
            - name: web
              containerPort: 2468
          securityContext:
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /health
              port: 2468
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 20
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
