apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-role.yaml
  - agent-sa.yaml
  - agent-rolebinding.yaml
  - agent-secret.yaml
  - agent-deploy.yaml
  - agent-svc.yaml
